language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="libglib2.0-dev gobject-introspection libgtk-3-0 libgranite-dev libsoup2.4-dev libjson-glib-dev libwingpanel-2.0-dev libswitchboard-2.0-dev libgeoclue-2-dev meson valac"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:juno-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja"

script:
 - echo BUILDS PASSED
